version: '3.7'
services:
    rtl-tcp:
        build:
            context: .
        ports:
            - "12340:1234"
        environment:
            TZ: "Asia/Tokyo"
        devices:
            - /dev/bus/usb:/dev/bus/usb
        tty: true
        restart: always